site_name: ITS Ontology - Location
site_description: A registry for documenting the ontology of ITS Location terms
repo_url: https://github.com/ISO-TC204/ontology-its-location-v1
nav:
- Home: index.md
- Area Pattern:
  - Area Pattern: area-pattern.md
  - Area By Circle: AreaByCircle.md
  - Area By Code: AreaByCode.md
  - Area By Grid: AreaByGrid.md
  - Area By Linear Boundaries: AreaByLinearBoundaries.md
  - Area By Multi Polygon: AreaByMultiPolygon.md
  - Area By Polygon: AreaByPolygon.md
  - Area By Rectangle: AreaByRectangle.md
  - Area Location: AreaLocation.md
  - Area Representation: AreaRepresentation.md
- Core Pattern:
  - Core Pattern: core-pattern.md
  - Coordinate Geometry: CoordinateGeometry.md
  - Coordinate Reference System: CoordinateReferenceSystem.md
  - Feature: Feature.md
  - Geometry: Geometry.md
  - Location: Location.md
  - Location Code: LocationCode.md
  - Location Group: LocationGroup.md
  - Location Thing: LocationThing.md
  - Spatial Object: SpatialObject.md
- Itinerary Pattern:
  - Itinerary Pattern: itinerary-pattern.md
  - Itinerary: Itinerary.md
  - Itinerary By Waypoints: ItineraryByWaypoints.md
  - Itinerary Code: ItineraryCode.md
  - Itinerary Representation: ItineraryRepresentation.md
  - Location List: LocationList.md
- Linear Pattern:
  - Linear Pattern: linear-pattern.md
  - Linear By Code: LinearByCode.md
  - Linear By Linear Ring: LinearByLinearRing.md
  - Linear By Line String: LinearByLineString.md
  - Linear By Multi Line String: LinearByMultiLineString.md
  - Linear By Point Representations: LinearByPointRepresentations.md
  - Linear By Points: LinearByPoints.md
  - Linear Location: LinearLocation.md
  - Linear Representation: LinearRepresentation.md
  - Offset Distance: OffsetDistance.md
  - Point By Linear Position: PointByLinearPosition.md
  - Point Location List: PointLocationList.md
  - Point Representation List: PointRepresentationList.md
- Point Pattern:
  - Point Pattern: point-pattern.md
  - Distance Accuracy: DistanceAccuracy.md
  - Elevation: Elevation.md
  - Elevation Accuracy: ElevationAccuracy.md
  - Elevation Height Code: ElevationHeightCode.md
  - Elevation Reference Code: ElevationReferenceCode.md
  - Measurement Error Code: MeasurementErrorCode.md
  - Point By Code: PointByCode.md
  - Point By Coordinates: PointByCoordinates.md
  - Point By Geo Coordinates: PointByGeoCoordinates.md
  - Point By Projected Coordinates: PointByProjectedCoordinates.md
  - Point Location: PointLocation.md
  - Point Representation: PointRepresentation.md
  - Position Accuracy: PositionAccuracy.md
  - Position Confidence Ellipse: PositionConfidenceEllipse.md
site_url: https://isotc204.org/ontology-its-location-v1/latest/
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: ''
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
